// Script to import players from Excel data into Supabase
// Run this once to populate the players table

import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://psnnycxzbqgvoxbmidic.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzbm55Y3h6YnFndm94Ym1pZGljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5MjEwMzcsImV4cCI6MjA3NjQ5NzAzN30.Pr_2HGXP7_logndnhASnT8w5lampw9XqUQacPLTxKVw';

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

const players = [
  { name: "Carnesecchi", team: "Atalanta", role: "P", fvm_value: 70 },
  { name: "Maignan", team: "Milan", role: "P", fvm_value: 81 },
  { name: "Svilar", team: "Roma", role: "P", fvm_value: 85 },
  { name: "Di Gregorio", team: "Juventus", role: "P", fvm_value: 78 },
  { name: "Skorupski", team: "Bologna", role: "P", fvm_value: 52 },
  { name: "Provedel", team: "Lazio", role: "P", fvm_value: 50 },
  { name: "Meret", team: "Napoli", role: "P", fvm_value: 79 },
  { name: "Butez", team: "Como", role: "P", fvm_value: 31 },
  { name: "De Gea", team: "Fiorentina", role: "P", fvm_value: 49 },
  { name: "Sommer", team: "Inter", role: "P", fvm_value: 65 },
  { name: "Caprile", team: "Cagliari", role: "P", fvm_value: 27 },
  { name: "Leali", team: "Genoa", role: "P", fvm_value: 25 },
  { name: "Falcone", team: "Lecce", role: "P", fvm_value: 24 },
  { name: "Montipò", team: "Verona", role: "P", fvm_value: 17 },
  { name: "Suzuki", team: "Parma", role: "P", fvm_value: 12 },
  { name: "Muric", team: "Sassuolo", role: "P", fvm_value: 16 },
  { name: "Audero", team: "Cremonese", role: "P", fvm_value: 21 },
  { name: "Israel", team: "Torino", role: "P", fvm_value: 20 },
  { name: "Semper", team: "Pisa", role: "P", fvm_value: 14 },
  { name: "Turati", team: "Sassuolo", role: "P", fvm_value: 1 },
  { name: "Sava", team: "Udinese", role: "P", fvm_value: 8 },
  { name: "Martinez Jo.", team: "Inter", role: "P", fvm_value: 12 },
  { name: "Milinkovic-Savic V.", team: "Napoli", role: "P", fvm_value: 20 },
  { name: "Okoye", team: "Udinese", role: "P", fvm_value: 10 },
  { name: "Terracciano", team: "Milan", role: "P", fvm_value: 1 },
  { name: "Silvestri", team: "Cremonese", role: "P", fvm_value: 1 },
  { name: "Rossi F.", team: "Atalanta", role: "P", fvm_value: 1 },
  { name: "Sportiello", team: "Atalanta", role: "P", fvm_value: 1 },
  { name: "Pessina Mas.", team: "Bologna", role: "P", fvm_value: 1 },
  { name: "Ravaglia F.", team: "Bologna", role: "P", fvm_value: 1 },
  { name: "Ciocci", team: "Cagliari", role: "P", fvm_value: 1 },
  { name: "Radunovic", team: "Cagliari", role: "P", fvm_value: 1 },
  { name: "Vigorito", team: "Como", role: "P", fvm_value: 1 },
  { name: "Nava", team: "Cremonese", role: "P", fvm_value: 1 },
  { name: "Martinelli T.", team: "Fiorentina", role: "P", fvm_value: 1 },
  { name: "Siegrist", team: "Genoa", role: "P", fvm_value: 1 },
  { name: "Sommariva", team: "Genoa", role: "P", fvm_value: 1 },
  { name: "Di Gennaro", team: "Inter", role: "P", fvm_value: 1 },
  { name: "Perin", team: "Juventus", role: "P", fvm_value: 1 },
  { name: "Pinsoglio", team: "Juventus", role: "P", fvm_value: 1 },
  { name: "Furlanetto", team: "Lazio", role: "P", fvm_value: 1 },
  { name: "Mandas", team: "Lazio", role: "P", fvm_value: 1 },
  { name: "Fruchtl", team: "Lecce", role: "P", fvm_value: 1 },
  { name: "Samooja", team: "Lecce", role: "P", fvm_value: 1 },
  { name: "Torriani", team: "Milan", role: "P", fvm_value: 1 },
  { name: "Contini", team: "Napoli", role: "P", fvm_value: 1 },
  { name: "Corvi", team: "Parma", role: "P", fvm_value: 1 },
  { name: "Rinaldi", team: "Parma", role: "P", fvm_value: 1 },
  { name: "Nicolas", team: "Pisa", role: "P", fvm_value: 1 },
  { name: "Scuffet", team: "Pisa", role: "P", fvm_value: 1 },
  { name: "Zelezny", team: "Roma", role: "P", fvm_value: 1 },
  { name: "Gollini", team: "Roma", role: "P", fvm_value: 1 },
  { name: "Satalino", team: "Sassuolo", role: "P", fvm_value: 1 },
  { name: "Paleari", team: "Torino", role: "P", fvm_value: 1 },
  { name: "Popa", team: "Torino", role: "P", fvm_value: 1 },
  { name: "Padelli", team: "Udinese", role: "P", fvm_value: 1 },
  { name: "Perilli", team: "Verona", role: "P", fvm_value: 1 },
  { name: "Vasquez D.", team: "Roma", role: "P", fvm_value: 1 },
  { name: "Nunziante", team: "Udinese", role: "P", fvm_value: 1 },
  { name: "Lezzerini", team: "Fiorentina", role: "P", fvm_value: 1 },
  { name: "Toniolo", team: "Verona", role: "P", fvm_value: 1 },
  { name: "Cavlina", team: "Como", role: "P", fvm_value: 1 },
  { name: "Dimarco", team: "Inter", role: "D", fvm_value: 112 },
  { name: "Dumfries", team: "Inter", role: "D", fvm_value: 100 },
  { name: "Bastoni", team: "Inter", role: "D", fvm_value: 81 },
  { name: "Gosens", team: "Fiorentina", role: "D", fvm_value: 40 },
  { name: "Bremer", team: "Juventus", role: "D", fvm_value: 37 },
  { name: "Wesley", team: "Roma", role: "D", fvm_value: 42 },
  { name: "Bellanova", team: "Atalanta", role: "D", fvm_value: 38 },
  { name: "Zortea", team: "Bologna", role: "D", fvm_value: 20 },
  { name: "Buongiorno", team: "Napoli", role: "D", fvm_value: 35 },
  { name: "Di Lorenzo", team: "Napoli", role: "D", fvm_value: 55 },
  { name: "Baschirotto", team: "Cremonese", role: "D", fvm_value: 29 },
  { name: "Pavlovic", team: "Milan", role: "D", fvm_value: 32 },
  { name: "Angelino", team: "Roma", role: "D", fvm_value: 37 },
  { name: "Solet", team: "Udinese", role: "D", fvm_value: 48 },
  { name: "Zappacosta", team: "Atalanta", role: "D", fvm_value: 22 },
  { name: "Mina", team: "Cagliari", role: "D", fvm_value: 21 },
  { name: "Carlos Augusto", team: "Inter", role: "D", fvm_value: 39 },
  { name: "Cambiaso", team: "Juventus", role: "D", fvm_value: 36 },
  { name: "Beukema", team: "Napoli", role: "D", fvm_value: 18 },
  { name: "Spinazzola", team: "Napoli", role: "D", fvm_value: 51 },
  { name: "Valeri", team: "Parma", role: "D", fvm_value: 30 },
  { name: "Coco", team: "Torino", role: "D", fvm_value: 18 },
  { name: "Hien", team: "Atalanta", role: "D", fvm_value: 31 },
  { name: "Luperto", team: "Cagliari", role: "D", fvm_value: 15 },
  { name: "Ranieri L.", team: "Fiorentina", role: "D", fvm_value: 17 },
  { name: "Kelly L.", team: "Juventus", role: "D", fvm_value: 25 },
  { name: "Tavares N.", team: "Lazio", role: "D", fvm_value: 27 },
  { name: "Mancini", team: "Roma", role: "D", fvm_value: 28 },
  { name: "N'Dicka", team: "Roma", role: "D", fvm_value: 25 },
  { name: "Celik", team: "Roma", role: "D", fvm_value: 22 },
  { name: "Akanji", team: "Inter", role: "D", fvm_value: 33 },
  { name: "Ahanor", team: "Atalanta", role: "D", fvm_value: 16 },
  { name: "Dodò", team: "Fiorentina", role: "D", fvm_value: 35 },
  { name: "Vasquez", team: "Genoa", role: "D", fvm_value: 20 },
  { name: "Martin", team: "Genoa", role: "D", fvm_value: 24 },
  { name: "Kalulu", team: "Juventus", role: "D", fvm_value: 32 },
  { name: "Gila", team: "Lazio", role: "D", fvm_value: 22 },
  { name: "Gabbia", team: "Milan", role: "D", fvm_value: 18 },
  { name: "Estupinan", team: "Milan", role: "D", fvm_value: 31 },
  { name: "Rrahmani", team: "Napoli", role: "D", fvm_value: 24 },
  { name: "Scalvini", team: "Atalanta", role: "D", fvm_value: 20 },
  { name: "Kossounou", team: "Atalanta", role: "D", fvm_value: 18 },
  { name: "Palestra", team: "Cagliari", role: "D", fvm_value: 17 },
  { name: "Holm", team: "Bologna", role: "D", fvm_value: 14 },
  { name: "Kempf", team: "Como", role: "D", fvm_value: 15 },
  { name: "Acerbi", team: "Inter", role: "D", fvm_value: 22 },
  { name: "De Vrij", team: "Inter", role: "D", fvm_value: 21 },
  { name: "Marusic", team: "Lazio", role: "D", fvm_value: 24 },
  { name: "Tomori", team: "Milan", role: "D", fvm_value: 24 },
  { name: "Olivera", team: "Napoli", role: "D", fvm_value: 12 },
  { name: "Delprato", team: "Parma", role: "D", fvm_value: 24 },
  { name: "Kristensen T.", team: "Udinese", role: "D", fvm_value: 13 },
  { name: "Idzes", team: "Sassuolo", role: "D", fvm_value: 18 },
  { name: "Heggem", team: "Bologna", role: "D", fvm_value: 23 },
  { name: "Djimsiti", team: "Atalanta", role: "D", fvm_value: 15 },
  { name: "Lucumì", team: "Bologna", role: "D", fvm_value: 17 },
  { name: "Miranda J.", team: "Bologna", role: "D", fvm_value: 15 },
  { name: "Valle", team: "Como", role: "D", fvm_value: 16 },
  { name: "De Winter", team: "Milan", role: "D", fvm_value: 12 },
  { name: "Gatti", team: "Juventus", role: "D", fvm_value: 17 },
  { name: "Cabal", team: "Juventus", role: "D", fvm_value: 17 },
  { name: "Joao Mario", team: "Juventus", role: "D", fvm_value: 10 },
  { name: "Romagnoli", team: "Lazio", role: "D", fvm_value: 23 },
  { name: "Circati", team: "Parma", role: "D", fvm_value: 15 },
  { name: "Angori", team: "Pisa", role: "D", fvm_value: 13 },
  { name: "Maripan", team: "Torino", role: "D", fvm_value: 14 },
  { name: "Biraghi", team: "Torino", role: "D", fvm_value: 12 },
  { name: "Cuadrado", team: "Pisa", role: "D", fvm_value: 12 },
  { name: "Vitik", team: "Bologna", role: "D", fvm_value: 13 },
  { name: "Vojvoda", team: "Como", role: "D", fvm_value: 16 },
  { name: "Bianchetti", team: "Cremonese", role: "D", fvm_value: 12 },
  { name: "Pezzella Giu.", team: "Cremonese", role: "D", fvm_value: 13 },
  { name: "Comuzzo", team: "Fiorentina", role: "D", fvm_value: 13 },
  { name: "Bisseck", team: "Inter", role: "D", fvm_value: 8 },
  { name: "Gaspar K.", team: "Lecce", role: "D", fvm_value: 15 },
  { name: "Tiago Gabriel", team: "Lecce", role: "D", fvm_value: 15 },
  { name: "Gallo", team: "Lecce", role: "D", fvm_value: 17 },
  { name: "Terracciano F.", team: "Cremonese", role: "D", fvm_value: 13 },
  { name: "Hermoso", team: "Roma", role: "D", fvm_value: 13 },
  { name: "Rensch", team: "Roma", role: "D", fvm_value: 16 },
  { name: "Walukiewicz", team: "Sassuolo", role: "D", fvm_value: 12 },
  { name: "Doig", team: "Sassuolo", role: "D", fvm_value: 18 },
  { name: "Ismajli", team: "Torino", role: "D", fvm_value: 12 },
  { name: "Lazaro", team: "Torino", role: "D", fvm_value: 19 },
  { name: "Kamara H.", team: "Udinese", role: "D", fvm_value: 15 },
  { name: "Bradaric", team: "Verona", role: "D", fvm_value: 10 },
  { name: "Goglichidze", team: "Udinese", role: "D", fvm_value: 12 },
  { name: "Gutierrez", team: "Napoli", role: "D", fvm_value: 11 },
  { name: "Diego Carlos", team: "Como", role: "D", fvm_value: 21 },
  { name: "Kolasinac", team: "Atalanta", role: "D", fvm_value: 18 },
  { name: "Zappa", team: "Cagliari", role: "D", fvm_value: 14 },
  { name: "Floriani Mussolini", team: "Cremonese", role: "D", fvm_value: 9 },
  { name: "Marì", team: "Fiorentina", role: "D", fvm_value: 10 },
  { name: "Pongracic", team: "Fiorentina", role: "D", fvm_value: 16 },
  { name: "Norton-Cuffy", team: "Genoa", role: "D", fvm_value: 20 },
  { name: "Pellegrini Lu.", team: "Lazio", role: "D", fvm_value: 11 },
  { name: "Caracciolo A.", team: "Pisa", role: "D", fvm_value: 12 },
  { name: "Muharemovic", team: "Sassuolo", role: "D", fvm_value: 10 },
  { name: "Pedersen", team: "Torino", role: "D", fvm_value: 10 },
  { name: "Bertola", team: "Udinese", role: "D", fvm_value: 11 },
  { name: "Kabasele", team: "Udinese", role: "D", fvm_value: 6 },
  { name: "Unai Nunez", team: "Verona", role: "D", fvm_value: 12 },
  { name: "Frese", team: "Verona", role: "D", fvm_value: 9 },
  { name: "Belghali", team: "Verona", role: "D", fvm_value: 16 },
  { name: "Nelsson", team: "Verona", role: "D", fvm_value: 12 },
  { name: "Bella-Kotchap", team: "Verona", role: "D", fvm_value: 7 },
  { name: "Bonfanti", team: "Pisa", role: "D", fvm_value: 7 },
  { name: "Posch", team: "Como", role: "D", fvm_value: 14 },
  { name: "De Silvestri", team: "Bologna", role: "D", fvm_value: 10 },
  { name: "Obert", team: "Cagliari", role: "D", fvm_value: 15 },
  { name: "Viti", team: "Fiorentina", role: "D", fvm_value: 8 },
  { name: "Sabelli", team: "Genoa", role: "D", fvm_value: 13 },
  { name: "Kouassi", team: "Lecce", role: "D", fvm_value: 9 },
  { name: "Veiga D.", team: "Lecce", role: "D", fvm_value: 10 },
  { name: "Juan Jesus", team: "Napoli", role: "D", fvm_value: 17 },
  { name: "Canestrelli", team: "Pisa", role: "D", fvm_value: 12 },
  { name: "Mateus Lusuardi", team: "Pisa", role: "D", fvm_value: 8 },
  { name: "Ehizibue", team: "Udinese", role: "D", fvm_value: 14 },
  { name: "Ramon", team: "Como", role: "D", fvm_value: 12 },
  { name: "Candè", team: "Sassuolo", role: "D", fvm_value: 11 },
  { name: "Athekame", team: "Milan", role: "D", fvm_value: 9 },
  { name: "Troilo", team: "Parma", role: "D", fvm_value: 9 },
  { name: "Tsimikas", team: "Roma", role: "D", fvm_value: 10 },
  { name: "Lamptey", team: "Fiorentina", role: "D", fvm_value: 5 },
  { name: "Nkounkou", team: "Torino", role: "D", fvm_value: 8 },
  { name: "Albiol", team: "Pisa", role: "D", fvm_value: 5 },
  { name: "Lykogiannis", team: "Bologna", role: "D", fvm_value: 13 },
  { name: "Idrissi R.", team: "Cagliari", role: "D", fvm_value: 5 },
  { name: "Van Der Brempt", team: "Como", role: "D", fvm_value: 7 },
  { name: "Ceccherini", team: "Cremonese", role: "D", fvm_value: 11 },
  { name: "Fortini", team: "Fiorentina", role: "D", fvm_value: 4 },
  { name: "Parisi", team: "Fiorentina", role: "D", fvm_value: 10 },
  { name: "Marcandalli", team: "Genoa", role: "D", fvm_value: 4 },
  { name: "Provstgaard", team: "Lazio", role: "D", fvm_value: 7 },
  { name: "Bartesaghi", team: "Milan", role: "D", fvm_value: 5 },
  { name: "Zanoli", team: "Udinese", role: "D", fvm_value: 11 },
  { name: "Valenti", team: "Parma", role: "D", fvm_value: 6 },
  { name: "Lovik", team: "Parma", role: "D", fvm_value: 11 },
  { name: "Calabresi", team: "Pisa", role: "D", fvm_value: 6 },
  { name: "Masina", team: "Torino", role: "D", fvm_value: 10 },
  { name: "Zemura", team: "Udinese", role: "D", fvm_value: 11 },
  { name: "Ostigard", team: "Genoa", role: "D", fvm_value: 13 },
  { name: "Ndiaye", team: "Parma", role: "D", fvm_value: 10 },
  { name: "Siebert", team: "Lecce", role: "D", fvm_value: 7 },
  { name: "Ziolkowski", team: "Roma", role: "D", fvm_value: 7 },
  { name: "Faye", team: "Cremonese", role: "D", fvm_value: 6 },
  { name: "Coulibaly W.", team: "Sassuolo", role: "D", fvm_value: 8 },
  { name: "Zè Pedro", team: "Cagliari", role: "D", fvm_value: 8 },
  { name: "Casale", team: "Bologna", role: "D", fvm_value: 8 },
  { name: "Di Pardo", team: "Cagliari", role: "D", fvm_value: 4 },
  { name: "Dossena", team: "Como", role: "D", fvm_value: 5 },
  { name: "Goldaniga", team: "Como", role: "D", fvm_value: 6 },
  { name: "Smolcic I.", team: "Como", role: "D", fvm_value: 9 },
  { name: "Folino", team: "Cremonese", role: "D", fvm_value: 5 },
  { name: "Barbieri", team: "Cremonese", role: "D", fvm_value: 9 },
  { name: "Darmian", team: "Inter", role: "D", fvm_value: 16 },
  { name: "Rugani", team: "Juventus", role: "D", fvm_value: 10 },
  { name: "Gigot", team: "Lazio", role: "D", fvm_value: 3 },
  { name: "Patric", team: "Lazio", role: "D", fvm_value: 6 },
  { name: "Lazzari", team: "Lazio", role: "D", fvm_value: 8 },
  { name: "Hysaj", team: "Lazio", role: "D", fvm_value: 8 },
  { name: "Ndaba", team: "Lecce", role: "D", fvm_value: 2 },
  { name: "Romagna", team: "Sassuolo", role: "D", fvm_value: 9 },
  { name: "Rui Modesto", team: "Udinese", role: "D", fvm_value: 4 },
  { name: "Ghilardi", team: "Roma", role: "D", fvm_value: 9 },
  { name: "Valentini N.", team: "Verona", role: "D", fvm_value: 9 },
  { name: "Ebosse", team: "Verona", role: "D", fvm_value: 9 },
  { name: "Bernasconi", team: "Atalanta", role: "D", fvm_value: 7 },
  { name: "Cham", team: "Verona", role: "D", fvm_value: 4 },
  { name: "Britschgi", team: "Parma", role: "D", fvm_value: 14 },
  { name: "Moreno Alb.", team: "Como", role: "D", fvm_value: 7 },
  { name: "Sernicola", team: "Cremonese", role: "D", fvm_value: 1 },
  { name: "Otoa", team: "Genoa", role: "D", fvm_value: 3 },
  { name: "Rouhi", team: "Juventus", role: "D", fvm_value: 4 },
  { name: "Jean", team: "Lecce", role: "D", fvm_value: 3 },
  { name: "Perez M.", team: "Lecce", role: "D", fvm_value: 1 },
  { name: "Marianucci", team: "Napoli", role: "D", fvm_value: 5 },
  { name: "Mazzocchi", team: "Napoli", role: "D", fvm_value: 5 },
  { name: "Coppola F.", team: "Pisa", role: "D", fvm_value: 4 },
  { name: "Mbambi", team: "Pisa", role: "D", fvm_value: 2 },
  { name: "Esteves T.", team: "Pisa", role: "D", fvm_value: 2 },
  { name: "Odenthal", team: "Sassuolo", role: "D", fvm_value: 12 },
  { name: "Paz Y.", team: "Sassuolo", role: "D", fvm_value: 5 },
  { name: "Pieragnolo", team: "Sassuolo", role: "D", fvm_value: 3 },
  { name: "Schuurs", team: "Torino", role: "D", fvm_value: 5 },
  { name: "Dembelè A.", team: "Torino", role: "D", fvm_value: 3 },
  { name: "Palma", team: "Udinese", role: "D", fvm_value: 7 },
  { name: "Slotsager", team: "Verona", role: "D", fvm_value: 5 },
  { name: "Oyegoke", team: "Verona", role: "D", fvm_value: 5 },
  { name: "Denoon", team: "Pisa", role: "D", fvm_value: 4 },
  { name: "Kouadio", team: "Fiorentina", role: "D", fvm_value: 1 },
  { name: "Rodriguez Ju.", team: "Cagliari", role: "D", fvm_value: 1 },
  { name: "Odogu", team: "Milan", role: "D", fvm_value: 5 },
  { name: "Palacios T.", team: "Inter", role: "D", fvm_value: 1 },
  { name: "Orsolini", team: "Bologna", role: "C", fvm_value: 243 },
  { name: "Pulisic", team: "Milan", role: "C", fvm_value: 245 },
  { name: "De Bruyne", team: "Napoli", role: "C", fvm_value: 170 },
  { name: "Paz N.", team: "Como", role: "C", fvm_value: 222 },
  { name: "Zaccagni", team: "Lazio", role: "C", fvm_value: 201 },
  { name: "McTominay", team: "Napoli", role: "C", fvm_value: 202 },
  { name: "Calhanoglu", team: "Inter", role: "C", fvm_value: 179 },
  { name: "Rabiot", team: "Milan", role: "C", fvm_value: 147 },
  { name: "Gudmundsson A.", team: "Fiorentina", role: "C", fvm_value: 64 },
  { name: "Conceicao", team: "Juventus", role: "C", fvm_value: 73 },
  { name: "Zambo Anguissa", team: "Napoli", role: "C", fvm_value: 85 },
  { name: "Odgaard", team: "Bologna", role: "C", fvm_value: 72 },
  { name: "Zhegrova", team: "Juventus", role: "C", fvm_value: 48 },
  { name: "Mandragora", team: "Fiorentina", role: "C", fvm_value: 43 },
  { name: "Thuram K.", team: "Juventus", role: "C", fvm_value: 71 },
  { name: "Saelemaekers", team: "Milan", role: "C", fvm_value: 80 },
  { name: "Modric", team: "Milan", role: "C", fvm_value: 65 },
  { name: "Politano", team: "Napoli", role: "C", fvm_value: 68 },
  { name: "Samardzic", team: "Atalanta", role: "C", fvm_value: 32 },
  { name: "Barella", team: "Inter", role: "C", fvm_value: 63 },
  { name: "Konè M.", team: "Roma", role: "C", fvm_value: 50 },
  { name: "Rowe", team: "Bologna", role: "C", fvm_value: 40 },
  { name: "Pasalic", team: "Atalanta", role: "C", fvm_value: 31 },
  { name: "Vandeputte", team: "Cremonese", role: "C", fvm_value: 30 },
  { name: "Vazquez", team: "Cremonese", role: "C", fvm_value: 26 },
  { name: "Fofana Y.", team: "Milan", role: "C", fvm_value: 45 },
  { name: "Pellegrini Lo.", team: "Roma", role: "C", fvm_value: 27 },
  { name: "Ederson D.S.", team: "Atalanta", role: "C", fvm_value: 39 },
  { name: "Frattesi", team: "Inter", role: "C", fvm_value: 23 },
  { name: "Locatelli", team: "Juventus", role: "C", fvm_value: 39 },
  { name: "Loftus-Cheek", team: "Milan", role: "C", fvm_value: 21 },
  { name: "Bernabè", team: "Parma", role: "C", fvm_value: 28 },
  { name: "Cristante", team: "Roma", role: "C", fvm_value: 37 },
  { name: "Vlasic", team: "Torino", role: "C", fvm_value: 27 },
  { name: "Sottil", team: "Lecce", role: "C", fvm_value: 33 },
  { name: "Bailey", team: "Roma", role: "C", fvm_value: 15 },
  { name: "Da Cunha", team: "Como", role: "C", fvm_value: 24 },
  { name: "Koopmeiners", team: "Juventus", role: "C", fvm_value: 23 },
  { name: "Isaksen", team: "Lazio", role: "C", fvm_value: 26 },
  { name: "Coulibaly L.", team: "Lecce", role: "C", fvm_value: 26 },
  { name: "Neres", team: "Napoli", role: "C", fvm_value: 20 },
  { name: "Fadera", team: "Sassuolo", role: "C", fvm_value: 10 },
  { name: "Atta", team: "Udinese", role: "C", fvm_value: 36 },
  { name: "Oristanio", team: "Parma", role: "C", fvm_value: 22 },
  { name: "Elmas", team: "Napoli", role: "C", fvm_value: 17 },
  { name: "De Roon", team: "Atalanta", role: "C", fvm_value: 33 },
  { name: "Freuler", team: "Bologna", role: "C", fvm_value: 28 },
  { name: "Folorunsho", team: "Cagliari", role: "C", fvm_value: 23 },
  { name: "Felici", team: "Cagliari", role: "C", fvm_value: 10 },
  { name: "Perrone", team: "Como", role: "C", fvm_value: 29 },
  { name: "Caqueret", team: "Como", role: "C", fvm_value: 14 },
  { name: "Fazzini", team: "Fiorentina", role: "C", fvm_value: 21 },
  { name: "Carboni V.", team: "Genoa", role: "C", fvm_value: 17 },
  { name: "Sucic P.", team: "Inter", role: "C", fvm_value: 24 },
  { name: "Guendouzi", team: "Lazio", role: "C", fvm_value: 20 },
  { name: "Pierotti", team: "Lecce", role: "C", fvm_value: 15 },
  { name: "Lobotka", team: "Napoli", role: "C", fvm_value: 29 },
  { name: "Ondrejka", team: "Parma", role: "C", fvm_value: 15 },
  { name: "Tramoni M.", team: "Pisa", role: "C", fvm_value: 22 },
  { name: "Konè I.", team: "Sassuolo", role: "C", fvm_value: 16 },
  { name: "Casadei", team: "Torino", role: "C", fvm_value: 20 },
  { name: "Jashari", team: "Milan", role: "C", fvm_value: 15 },
  { name: "Zaniolo", team: "Udinese", role: "C", fvm_value: 23 },
  { name: "Fabbian", team: "Bologna", role: "C", fvm_value: 16 },
  { name: "Ferguson", team: "Bologna", role: "C", fvm_value: 21 },
  { name: "Gaetano", team: "Cagliari", role: "C", fvm_value: 11 },
  { name: "Ellertsson", team: "Genoa", role: "C", fvm_value: 22 },
  { name: "Gronbaek", team: "Genoa", role: "C", fvm_value: 12 },
  { name: "Mkhitaryan", team: "Inter", role: "C", fvm_value: 31 },
  { name: "Dele-Bashiru", team: "Lazio", role: "C", fvm_value: 15 },
  { name: "Ricci S.", team: "Milan", role: "C", fvm_value: 16 },
  { name: "Gilmour", team: "Napoli", role: "C", fvm_value: 21 },
  { name: "Sohm", team: "Fiorentina", role: "C", fvm_value: 18 },
  { name: "Serdar", team: "Verona", role: "C", fvm_value: 15 },
  { name: "Stengs", team: "Pisa", role: "C", fvm_value: 14 },
  { name: "Nicolussi Caviglia", team: "Fiorentina", role: "C", fvm_value: 30 },
  { name: "Frendrup", team: "Genoa", role: "C", fvm_value: 25 },
  { name: "Zalewski", team: "Atalanta", role: "C", fvm_value: 37 },
  { name: "McKennie", team: "Juventus", role: "C", fvm_value: 19 },
  { name: "Cataldi", team: "Lazio", role: "C", fvm_value: 22 },
  { name: "Rovella", team: "Lazio", role: "C", fvm_value: 18 },
  { name: "Tete Morente", team: "Lecce", role: "C", fvm_value: 13 },
  { name: "Akinsanmiro", team: "Pisa", role: "C", fvm_value: 17 },
  { name: "Thorstvedt", team: "Sassuolo", role: "C", fvm_value: 23 },
  { name: "Lovric", team: "Udinese", role: "C", fvm_value: 16 },
  { name: "Ekkelenkamp", team: "Udinese", role: "C", fvm_value: 14 },
  { name: "Lorran", team: "Pisa", role: "C", fvm_value: 10 },
  { name: "Maldini", team: "Atalanta", role: "C", fvm_value: 15 },
  { name: "Bernardeschi", team: "Bologna", role: "C", fvm_value: 19 },
  { name: "Adopo", team: "Cagliari", role: "C", fvm_value: 15 },
  { name: "Collocolo", team: "Cremonese", role: "C", fvm_value: 15 },
  { name: "Malinovskyi", team: "Genoa", role: "C", fvm_value: 21 },
  { name: "Musah", team: "Atalanta", role: "C", fvm_value: 13 },
  { name: "Tourè I.", team: "Pisa", role: "C", fvm_value: 24 },
  { name: "El Aynaoui", team: "Roma", role: "C", fvm_value: 17 },
  { name: "El Shaarawy", team: "Roma", role: "C", fvm_value: 15 },
  { name: "Baldanzi", team: "Roma", role: "C", fvm_value: 16 },
  { name: "Volpato", team: "Sassuolo", role: "C", fvm_value: 15 },
  { name: "Anjorin", team: "Torino", role: "C", fvm_value: 11 },
  { name: "Brescianini", team: "Atalanta", role: "C", fvm_value: 14 },
  { name: "Moro N.", team: "Bologna", role: "C", fvm_value: 21 },
  { name: "Pobega", team: "Bologna", role: "C", fvm_value: 17 },
  { name: "Deiola", team: "Cagliari", role: "C", fvm_value: 12 },
  { name: "Prati", team: "Cagliari", role: "C", fvm_value: 19 },
  { name: "Baturina", team: "Como", role: "C", fvm_value: 11 },
  { name: "Fagioli", team: "Fiorentina", role: "C", fvm_value: 14 },
  { name: "Messias", team: "Genoa", role: "C", fvm_value: 11 },
  { name: "Stanciu", team: "Genoa", role: "C", fvm_value: 13 },
  { name: "Luis Henrique", team: "Inter", role: "C", fvm_value: 15 },
  { name: "Ramadani", team: "Lecce", role: "C", fvm_value: 12 },
  { name: "Berisha M.", team: "Lecce", role: "C", fvm_value: 11 },
  { name: "Helgason", team: "Lecce", role: "C", fvm_value: 5 },
  { name: "Zerbin", team: "Cremonese", role: "C", fvm_value: 24 },
  { name: "Reijnders", team: "Milan", role: "C", fvm_value: 68 },
  { name: "Anguissa", team: "Napoli", role: "C", fvm_value: 36 },
  { name: "Ndoye", team: "Bologna", role: "C", fvm_value: 65 },
  { name: "Suslov", team: "Verona", role: "C", fvm_value: 23 },
  { name: "Oliviero", team: "Sassuolo", role: "C", fvm_value: 13 },
  { name: "Pizarro T.", team: "Udinese", role: "C", fvm_value: 20 },
  { name: "Mosquera", team: "Verona", role: "C", fvm_value: 17 },
  { name: "Harroui", team: "Verona", role: "C", fvm_value: 15 },
  { name: "Vignato S.", team: "Cagliari", role: "C", fvm_value: 7 },
  { name: "Njoh", team: "Como", role: "C", fvm_value: 7 },
  { name: "Aliev", team: "Como", role: "C", fvm_value: 8 },
  { name: "Dickmann", team: "Cremonese", role: "C", fvm_value: 10 },
  { name: "Bistrovic", team: "Cremonese", role: "C", fvm_value: 7 },
  { name: "Kayode", team: "Fiorentina", role: "C", fvm_value: 6 },
  { name: "Richardson", team: "Fiorentina", role: "C", fvm_value: 11 },
  { name: "Papadopoulos", team: "Genoa", role: "C", fvm_value: 5 },
  { name: "Masala", team: "Genoa", role: "C", fvm_value: 14 },
  { name: "Zielinski", team: "Inter", role: "C", fvm_value: 21 },
  { name: "Asllani", team: "Inter", role: "C", fvm_value: 11 },
  { name: "Douglas Luiz", team: "Juventus", role: "C", fvm_value: 13 },
  { name: "Weah", team: "Juventus", role: "C", fvm_value: 11 },
  { name: "Tchaouna", team: "Lazio", role: "C", fvm_value: 11 },
  { name: "Noslin", team: "Lazio", role: "C", fvm_value: 11 },
  { name: "Castrovilli", team: "Lazio", role: "C", fvm_value: 7 },
  { name: "Marchwinski", team: "Lecce", role: "C", fvm_value: 8 },
  { name: "Morente", team: "Lecce", role: "C", fvm_value: 5 },
  { name: "Oudin", team: "Lecce", role: "C", fvm_value: 7 },
  { name: "Chukwueze", team: "Milan", role: "C", fvm_value: 13 },
  { name: "Okafor", team: "Milan", role: "C", fvm_value: 7 },
  { name: "Jimenez A.", team: "Milan", role: "C", fvm_value: 9 },
  { name: "Spinazzola L.", team: "Napoli", role: "C", fvm_value: 4 },
  { name: "Raspadori", team: "Napoli", role: "C", fvm_value: 24 },
  { name: "Ngonge", team: "Napoli", role: "C", fvm_value: 10 },
  { name: "Svanberg", team: "Parma", role: "C", fvm_value: 21 },
  { name: "Keita B.", team: "Parma", role: "C", fvm_value: 14 },
  { name: "Cancellieri", team: "Parma", role: "C", fvm_value: 16 },
  { name: "Almqvist", team: "Parma", role: "C", fvm_value: 11 },
  { name: "Hainaut", team: "Parma", role: "C", fvm_value: 14 },
  { name: "Camara A.", team: "Parma", role: "C", fvm_value: 12 },
  { name: "Mlakar", team: "Pisa", role: "C", fvm_value: 15 },
  { name: "Vignato E.", team: "Pisa", role: "C", fvm_value: 7 },
  { name: "Abildgaard", team: "Pisa", role: "C", fvm_value: 8 },
  { name: "Arena", team: "Pisa", role: "C", fvm_value: 6 },
  { name: "Leris", team: "Pisa", role: "C", fvm_value: 7 },
  { name: "Pisilli", team: "Roma", role: "C", fvm_value: 10 },
  { name: "Le Fee", team: "Roma", role: "C", fvm_value: 13 },
  { name: "Soulè", team: "Roma", role: "C", fvm_value: 9 },
  { name: "Shomurodov", team: "Roma", role: "C", fvm_value: 2 },
  { name: "Pierini", team: "Sassuolo", role: "C", fvm_value: 6 },
  { name: "Iannoni", team: "Sassuolo", role: "C", fvm_value: 7 },
  { name: "Mulattieri", team: "Sassuolo", role: "C", fvm_value: 6 },
  { name: "D'Andrea", team: "Sassuolo", role: "C", fvm_value: 8 },
  { name: "Seck", team: "Torino", role: "C", fvm_value: 11 },
  { name: "Tameze", team: "Torino", role: "C", fvm_value: 8 },
  { name: "Dembelè Y.", team: "Torino", role: "C", fvm_value: 6 },
  { name: "Linetty", team: "Torino", role: "C", fvm_value: 8 },
  { name: "Ricci G.", team: "Torino", role: "C", fvm_value: 9 },
  { name: "Gineitis", team: "Torino", role: "C", fvm_value: 10 },
  { name: "Lazetic", team: "Torino", role: "C", fvm_value: 3 },
  { name: "Payero", team: "Udinese", role: "C", fvm_value: 12 },
  { name: "Abankwah", team: "Udinese", role: "C", fvm_value: 11 },
  { name: "Karlstrom", team: "Udinese", role: "C", fvm_value: 9 },
  { name: "Atta J.", team: "Udinese", role: "C", fvm_value: 9 },
  { name: "Iker Bravo", team: "Udinese", role: "C", fvm_value: 7 },
  { name: "Kastanos", team: "Verona", role: "C", fvm_value: 15 },
  { name: "Duda", team: "Verona", role: "C", fvm_value: 15 },
  { name: "Tengstedt", team: "Verona", role: "C", fvm_value: 8 },
  { name: "Dani Silva", team: "Verona", role: "C", fvm_value: 9 },
  { name: "Livramento", team: "Verona", role: "C", fvm_value: 11 },
  { name: "Magnani", team: "Verona", role: "C", fvm_value: 8 },
  { name: "Coppola M.", team: "Verona", role: "C", fvm_value: 7 },
  { name: "Perrone G.", team: "Verona", role: "C", fvm_value: 4 },
  { name: "Retegui", team: "Atalanta", role: "A", fvm_value: 187 },
  { name: "Kvaratskhelia", team: "Napoli", role: "A", fvm_value: 176 },
  { name: "Lukaku", team: "Napoli", role: "A", fvm_value: 165 },
  { name: "Thuram M.", team: "Inter", role: "A", fvm_value: 164 },
  { name: "Vlahovic", team: "Juventus", role: "A", fvm_value: 132 },
  { name: "Dovbyk", team: "Roma", role: "A", fvm_value: 115 },
  { name: "Morata", team: "Milan", role: "A", fvm_value: 97 },
  { name: "Lautaro", team: "Inter", role: "A", fvm_value: 93 },
  { name: "Nico Gonzalez", team: "Juventus", role: "A", fvm_value: 77 },
  { name: "Lookman", team: "Atalanta", role: "A", fvm_value: 73 },
  { name: "Dybala", team: "Roma", role: "A", fvm_value: 64 },
  { name: "Castro", team: "Bologna", role: "A", fvm_value: 63 },
  { name: "Kean", team: "Fiorentina", role: "A", fvm_value: 62 },
  { name: "Esposito Seb.", team: "Torino", role: "A", fvm_value: 62 },
  { name: "Abraham", team: "Milan", role: "A", fvm_value: 58 },
  { name: "Dia", team: "Lazio", role: "A", fvm_value: 54 },
  { name: "Belotti", team: "Como", role: "A", fvm_value: 47 },
  { name: "Piccoli", team: "Cagliari", role: "A", fvm_value: 47 },
  { name: "Pinamonti", team: "Genoa", role: "A", fvm_value: 46 },
  { name: "Krstovic", team: "Lecce", role: "A", fvm_value: 41 },
  { name: "Adams", team: "Torino", role: "A", fvm_value: 40 },
  { name: "Cutrone", team: "Como", role: "A", fvm_value: 40 },
  { name: "Bonny", team: "Parma", role: "A", fvm_value: 39 },
  { name: "Taremi", team: "Inter", role: "A", fvm_value: 39 },
  { name: "Ekuban", team: "Genoa", role: "A", fvm_value: 33 },
  { name: "Beltran", team: "Fiorentina", role: "A", fvm_value: 32 },
  { name: "Kessie", team: "Fiorentina", role: "A", fvm_value: 31 },
  { name: "Lucca", team: "Udinese", role: "A", fvm_value: 31 },
  { name: "Sanabria", team: "Torino", role: "A", fvm_value: 30 },
  { name: "Simeone", team: "Napoli", role: "A", fvm_value: 28 },
  { name: "Njie", team: "Lecce", role: "A", fvm_value: 23 },
  { name: "Yildiz", team: "Juventus", role: "A", fvm_value: 22 },
  { name: "Noslin Ti.", team: "Verona", role: "A", fvm_value: 22 },
  { name: "Onyedika", team: "Parma", role: "A", fvm_value: 21 },
  { name: "Dallinga", team: "Bologna", role: "A", fvm_value: 20 },
  { name: "De Ketelaere", team: "Atalanta", role: "A", fvm_value: 19 },
  { name: "Kouamè", team: "Fiorentina", role: "A", fvm_value: 19 },
  { name: "Vitinha Fer.", team: "Genoa", role: "A", fvm_value: 18 },
  { name: "Coda", team: "Cremonese", role: "A", fvm_value: 18 },
  { name: "Colombo", team: "Bologna", role: "A", fvm_value: 17 },
  { name: "Correa", team: "Inter", role: "A", fvm_value: 17 },
  { name: "Pedro", team: "Lazio", role: "A", fvm_value: 17 },
  { name: "Pavoletti", team: "Cagliari", role: "A", fvm_value: 16 },
  { name: "Lapadula", team: "Cagliari", role: "A", fvm_value: 16 },
  { name: "Ianai", team: "Pisa", role: "A", fvm_value: 15 },
  { name: "Antiste", team: "Sassuolo", role: "A", fvm_value: 15 },
  { name: "Cerri", team: "Como", role: "A", fvm_value: 14 },
  { name: "Fabregas C.", team: "Como", role: "A", fvm_value: 14 },
  { name: "Angulo", team: "Cremonese", role: "A", fvm_value: 14 },
  { name: "Johnsen", team: "Cremonese", role: "A", fvm_value: 13 },
  { name: "Lasagna", team: "Sassuolo", role: "A", fvm_value: 13 },
  { name: "Tongya", team: "Verona", role: "A", fvm_value: 12 },
  { name: "Pohjanpalo", team: "Sassuolo", role: "A", fvm_value: 11 },
  { name: "Kamate", team: "Torino", role: "A", fvm_value: 11 },
  { name: "Sarr", team: "Verona", role: "A", fvm_value: 11 },
  { name: "Camarda", team: "Milan", role: "A", fvm_value: 10 },
  { name: "Esposito Fra.", team: "Como", role: "A", fvm_value: 10 },
  { name: "Ikone", team: "Fiorentina", role: "A", fvm_value: 10 },
  { name: "Davis", team: "Udinese", role: "A", fvm_value: 10 },
  { name: "Pellegri", team: "Lecce", role: "A", fvm_value: 9 },
  { name: "Dorgu", team: "Lecce", role: "A", fvm_value: 9 },
  { name: "Rebic", team: "Lecce", role: "A", fvm_value: 9 },
  { name: "Man", team: "Parma", role: "A", fvm_value: 9 },
  { name: "Kouan", team: "Pisa", role: "A", fvm_value: 9 },
  { name: "Bonfanti N.", team: "Pisa", role: "A", fvm_value: 9 },
  { name: "Lind", team: "Pisa", role: "A", fvm_value: 9 },
  { name: "Arnautovic", team: "Inter", role: "A", fvm_value: 8 },
  { name: "Mihaila", team: "Parma", role: "A", fvm_value: 8 },
  { name: "Charpentier", team: "Parma", role: "A", fvm_value: 8 },
  { name: "Holm", team: "Verona", role: "A", fvm_value: 8 },
  { name: "Akpa Akpro", team: "Verona", role: "A", fvm_value: 8 },
  { name: "Azzi", team: "Atalanta", role: "A", fvm_value: 7 },
  { name: "Erlic", team: "Bologna", role: "A", fvm_value: 7 },
  { name: "Calligaris", team: "Cagliari", role: "A", fvm_value: 7 },
  { name: "Viola", team: "Cagliari", role: "A", fvm_value: 7 },
  { name: "Kingstone", team: "Como", role: "A", fvm_value: 7 },
  { name: "Strefezza", team: "Como", role: "A", fvm_value: 7 },
  { name: "Colley", team: "Cremonese", role: "A", fvm_value: 7 },
  { name: "Oyono", team: "Genoa", role: "A", fvm_value: 7 },
  { name: "Vogliacco", team: "Genoa", role: "A", fvm_value: 7 },
  { name: "Perisan", team: "Lecce", role: "A", fvm_value: 7 },
  { name: "Kristovic", team: "Lecce", role: "A", fvm_value: 7 },
  { name: "Morleo", team: "Parma", role: "A", fvm_value: 7 },
  { name: "Palombi", team: "Pisa", role: "A", fvm_value: 7 },
  { name: "Capradossi", team: "Pisa", role: "A", fvm_value: 7 },
  { name: "Bertinato", team: "Sassuolo", role: "A", fvm_value: 7 },
  { name: "Moro G.", team: "Sassuolo", role: "A", fvm_value: 7 },
  { name: "Russo F.", team: "Sassuolo", role: "A", fvm_value: 7 },
  { name: "Tuia", team: "Verona", role: "A", fvm_value: 7 },
  { name: "Coppola D.", team: "Verona", role: "A", fvm_value: 7 },
];

async function importPlayers() {
  console.log('Starting import of 539 players...');
  
  // Insert in batches of 100
  const batchSize = 100;
  for (let i = 0; i < players.length; i += batchSize) {
    const batch = players.slice(i, i + batchSize);
    const { error } = await supabase.from('players').insert(batch);
    
    if (error) {
      console.error(`Error inserting batch ${i / batchSize + 1}:`, error);
    } else {
      console.log(`Imported ${Math.min(i + batchSize, players.length)} / ${players.length} players`);
    }
  }
  
  console.log('Import completed!');
}

importPlayers();
